[build]
  command = "CI=false npm install --prefix client && npm run build --prefix client"  # or your build command
  publish = "client/build"  # or your build output directory

[context.production.environment]
  NODE_ENV = "production"
  CI = "false"
